### ISSUE TITLE
test with EK campaign

### ISSUE THREAD

**Issue by totoroha** [nao-sec/mal_getter#1]
I'm trying to test your script with this campaign:
https://umbrella.cisco.com/blog/2017/03/29/seamless-campaign-delivers-ramnit-via-rig-ek/

But this is the error that i got:
:~/mal_getter$ php main.php HookAds rig  http://forexo-click.info
main.php Undefined Campaign

can you help me with this?

**Comment by koike** [comment]
mal_getter does not support HookAds Campaign
Supported are EITest, GoodMan, Decimal IP and Seamless

If you know what kind of link structure it is, you can add it based on that information
